FROM python:3.10-slim

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    openssh-client \
    openssh-server \
    libpq-dev \
    gcc \
    wget \
    unzip \
    ssh 

# Установка рабочего каталога
WORKDIR /backend

# Копирование файла requirements.txt в контейнер
COPY requirements.txt /backend/requirements.txt

# Обновление pip и установка зависимостей Python
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Копирование файлов проекта
COPY . /backend/

# Копирование скрипта entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Установка скрипта entrypoint как команды по умолчанию
ENTRYPOINT ["python", "/backend/main.py"]