"""Добавление экстрегов

Revision ID: 15add4a2b4df
Revises: fa0c85c18553
Create Date: 2025-01-23 18:44:24.675412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15add4a2b4df'
down_revision: Union[str, None] = 'fa0c85c18553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extreg_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extreg_adress', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extreg_list')
    # ### end Alembic commands ###
