"""test3

Revision ID: a67f166e4e88
Revises: ed5486716c28
Create Date: 2025-01-14 19:45:02.415933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67f166e4e88'
down_revision: Union[str, None] = 'ed5486716c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sipun_login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'sipun_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'Login_ssh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'key_ssh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'key_ssh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'Login_ssh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'sipun_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'sipun_login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
